spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public
        format_sql: true
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/realms/ecommerce

  datasource:
    username: postgres
    password: 123
    url: jdbc:postgresql://localhost:5432/ecommerce_db
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

server:
  port: 8085

# Configuration Keycloak
keycloak:
  auth-server-url: http://localhost:8083/realms/ecommerce
  realm: ecommerce
  resource: user-service
  credentials:
    secret: ZA7MHj3y6xDnbMJ3BRjW7DahshDkY7IR
  use-resource-role-mappings: true
  bearer-only: true



