server:
  port: 8086

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888
      fail-fast: true

# Eureka client configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Twilio configuration - Replace with your Twilio credentials
twilio:
  account-sid: ${TWILIO_ACCOUNT_SID:your_account_sid}
  auth-token: ${TWILIO_AUTH_TOKEN:your_auth_token}
  phone-number: ${TWILIO_PHONE_NUMBER:your_twilio_phone_number}

# Kafka topics
app:
  kafka:
    topics:
      payment-completed: payment-completed-topic
      order-shipped: order-shipped-topic

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always