server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MahaDaiki/Ecommerce_Microservice
          default-label: main
          clone-on-start: true
          search-paths: '{application}'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# Configuration pour Vault (pour les secrets)
vault:
  uri: http://localhost:8200
  token: